# Generated by Django 4.2 on 2023-06-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codeshef',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hackerrank',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
    ]
